export const skillsData = [
  { name: 'Go', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'Rust', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg' },
  { name: 'Python', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg' },
  { name: 'Java', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
  { name: 'JavaScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg' },
  { name: 'TypeScript', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg' },
  { name: 'SQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
  { name: 'Gin', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'gRPC', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grpc/grpc-original.svg' },
  { name: 'gqlgen', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg' },
  { name: 'GraphQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg' },
  { name: 'GORM', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'Twirp', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'Spring Boot', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg' },
  { name: 'React', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg' },
  { name: 'REST APIs', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg' },
  { name: 'PostgreSQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg' },
  { name: 'MySQL', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg' },
  { name: 'Redis', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg' },
  { name: 'MongoDB', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg' },
  { name: 'Kafka', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg' },
  { name: 'AWS Lambda', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg' },
  { name: 'AWS CDK', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg' },
  { name: 'GCP', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg' },
  { name: 'Docker', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg' },
  { name: 'OpenShift', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg' },
  { name: 'CI/CD', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/githubactions/githubactions-original.svg' },
  { name: 'Microservices', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg' },
  { name: 'Distributed Systems', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg' },
  { name: 'Testify', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'GoMock', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'Mockgen', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/go/go-original.svg' },
  { name: 'JUnit 5', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
  { name: 'Mockito', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg' },
  { name: 'Tree-sitter', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg' },
  { name: 'Static Analysis', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rust/rust-original.svg' },
  { name: 'Git', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg' },
  { name: 'GitHub', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg' },
  { name: 'Bitbucket', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg' },
  { name: 'JIRA', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg' },
  { name: 'Confluence', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/confluence/confluence-original.svg' },
  { name: 'GitHub Copilot', icon: 'https://cdn.simpleicons.org/githubcopilot/888888' },
  { name: 'Windsurf', icon: 'https://cdn.simpleicons.org/windsurf/888888' },
  { name: 'Cursor', icon: 'https://cdn.simpleicons.org/cursor/888888' },
  { name: 'Codex' },
  { name: 'Opencode', icon: 'https://cdn.simpleicons.org/opencode/888888' },
  { name: 'Antigravity' },
  { name: 'Agile/Scrum', icon: 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg' },
];

/** High-signal skills shown first. */
export const primarySkills = [
  'Go',
  'Rust',
  'Python',
  'Java',
  'gRPC',
  'GraphQL',
  'Spring Boot',
  'PostgreSQL',
  'Redis',
  'Kafka',
  'AWS Lambda',
  'Docker',
  'Microservices',
];

export const skillGroups = [
  {
    label: 'languages',
    skills: ['Go', 'Rust', 'Python', 'Java', 'JavaScript', 'TypeScript', 'SQL'],
  },
  {
    label: 'frameworks',
    skills: ['Gin', 'gRPC', 'gqlgen', 'GraphQL', 'GORM', 'Twirp', 'Spring Boot', 'React', 'REST APIs'],
  },
  {
    label: 'data & messaging',
    skills: ['PostgreSQL', 'MySQL', 'Redis', 'MongoDB', 'Kafka'],
  },
  {
    label: 'cloud & devops',
    skills: ['AWS Lambda', 'AWS CDK', 'GCP', 'Docker', 'OpenShift', 'CI/CD', 'Microservices', 'Distributed Systems'],
  },
  {
    label: 'testing & analysis',
    skills: ['Testify', 'GoMock', 'Mockgen', 'JUnit 5', 'Mockito', 'Tree-sitter', 'Static Analysis'],
  },
  {
    label: 'tools & ai',
    skills: ['Git', 'GitHub', 'Bitbucket', 'JIRA', 'Confluence', 'GitHub Copilot', 'Windsurf', 'Cursor', 'Codex', 'Opencode', 'Antigravity', 'Agile/Scrum'],
  },
];

export const experienceData = [
  {
    company: 'CitiusTech · Mumbai, India',
    role: 'Senior Golang Developer',
    duration: 'Aug 2024 - Present',
    highlights: [
      'Shipped 40+ AWS Lambda microservices (gRPC + GraphQL/gqlgen) on the Patient Care Journey core team.',
      'Cut feature turnaround 30–40% with oneforall — local containerized debugging for Lambda services.',
      'Projected $2K–$4K/year savings vs third-party APIs by open-sourcing GoPDFSuit (internal PDF engine → OSS).',
      'Halved time-to-understand legacy codebases with GoMindMapper dependency mapping.',
      'Cut ticket grooming ~40% with an AI knowledge base that turns docs and notes into context-rich Jira briefs.',
      'Cut new-hire ramp-up from 4 weeks to under 2 via structured onboarding and knowledge transfer.',
    ],
  },
  {
    company: 'NSEIT · Mumbai, India',
    role: 'Associate System Analyst',
    duration: 'Feb 2020 - Jul 2024',
    highlights: [
      '4+ years in Java and Python: reporting (JasperReports, ReportLab), Spring Boot APIs, and workflow automation.',
      'Built TDOS exam monitoring (Spring Boot + HTTP/2 push) for PAN-India live exams.',
      'Led Servlet → Spring Boot/Angular and JBoss → WildFly modernization with STQC compliance.',
      'Cut bulk candidate search from days to 15 minutes with 40+ Python/Java utilities.',
    ],
  },
];

export const interestsData = [
  { name: 'reading', emoji: '📚' },
  { name: 'cycling', emoji: '🚴' },
  { name: 'music', emoji: '🎵' },
  { name: 'exploring tech', emoji: '🔭' },
  { name: 'chess', emoji: '♟️' },
  { name: 'space', emoji: '🚀' },
];